---

- name: Install supervisor
  apt: 
    pkg: ['supervisor'] 
    update_cache: "{{ update_apt_cache }}" 
    force: yes 
    state: latest
  tags:
    - packages
    - supervisor

- name: Ensure supervisor service is started
  service: name=supervisor state=started enabled=yes
  tags: 
    - supervisor
    - service
