---
# base -------------------------------------------------------------------------
timezone: Europe/Berlin
language_pack: language-pack-de

# common -----------------------------------------------------------------------
project_name: djangotest
application_name: "{{ project_name}}"

# web --------------------------------------------------------------------------
git_repo: https://github.com/RayCrafter/djangotest.git
git_branch: develop
setup_git_repo: true

virtualenv_root: "/webapps"
virtualenv_path: "{{ virtualenv_root }}/{{ application_name }}"
project_path: "{{ virtualenv_path }}/{{ project_name }}"

requirements_file: "{{ project_path }}/requirements.txt"

superuser_name: david
superuser_email: zuber.david@gmx.de

db_user: "{{ application_name }}"
db_name: "{{ application_name }}"

# Nginx settings
nginx_static_dir: "{{ virtualenv_path }}/static/"
nginx_media_dir: "{{ virtualenv_path }}/media/"

# rabbitmq role settings
rabbitmq_admin_user: admin
rabbitmq_host: localhost
rabbitmq_application_vhost: "{{ application_name }}"
rabbitmq_application_user: "{{ application_name }}"

# Django settings
django_settings_file: "config.settings.production"
django_run_syncdb: false
django_run_db_migrations: yes
django_run_collectstatic: yes
django_email_host: ~
django_email_port: 1025
django_email_host_user: ~
django_broker_url: "amqp://{{ rabbitmq_application_user }}:{{ rabbitmq_application_password }}@{{ rabbitmq_host}}/{{ rabbitmq_application_vhost }}"

# Django Environment varoiables
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  MEDIA_ROOT: "{{ nginx_media_dir }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  DATABASE_URL: "postgres://{{ db_user }}:{{ db_password}}@{{ db_host }}:5432/{{ db_name }}"
  DJANGO_EMAIL_HOST: "{{ django_email_host|default(omit) }}"
  EMAIL_PORT: "{{ django_email_port}}"
  EMAIL_HOST_USER: "{{ django_email_host_user|default(omit) }}"
  EMAIL_HOST_PASSWORD: "{{ django_email_host_password|default(omit) }}"
  DJANGO_DEFAULT_FROM_EMAIL: "{{ application_name}} <noreply@{{ ansible_eth1.ipv4.address }}>"
  BROKER_URL: "{{ django_broker_url|default(omit) }}"


# celery -----------------------------------------------------------------------
celery_num_workers: 2

# gridftp ----------------------------------------------------------------------
gridftp_user: '{{ gunicorn_user }}'
