---

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}
  tags: packages

- name: Run the Django syncdb command
  django_manage:
    command: syncdb
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment
  when: django_run_syncdb is defined and django_run_syncdb
  tags: django.syncdb

- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment
  when: django_run_db_migrations is defined and django_run_db_migrations
  tags: django.migrate

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment
  when: django_run_collectstatic is defined and django_run_collectstatic
  tags: django.collectstatic

- name: Copy createsuperuser script
  template: src=django_createsuperuser.py
            dest="{{ project_path }}"

- name: Create superuser
  shell: ". {{ virtualenv_path }}/bin/activate && python ./django_createsuperuser.py"
  args:
    chdir: "{{ project_path }}"
  environment: django_environment