---
git_repo: https://github.com/RayCrafter/djangotest.git
git_branch: master
setup_git_repo: true

project_name: djangotest
application_name: "{{ project_name }}"
virtualenv_root: "/webapps"
virtualenv_path: "{{ virtualenv_root }}/{{ application_name }}"
project_path: "{{ virtualenv_path }}/{{ project_name }}"
requirements_file: "{{ project_path }}/requirements.txt"

superuser_name: superuser
superuser_email: superuser@example.com
superuser_password: password

db_user: "{{ application_name }}"
db_name: "{{ application_name }}"
db_password: password

web_user: "{{ application_name }}"
web_group: webapps

# Nginx settings
nginx_static_dir: "{{ virtualenv_path }}/static/"
nginx_media_dir: "{{ virtualenv_path }}/media/"

# Django settings
django_settings_file: "config.settings.production"
django_wsgi_file: config.wsgi
django_secret_key: "akr2icmg1n8%z^3fe3c+)5d0(t^cy-2_25rrl35a7@!scna^1#"
django_run_syncdb: false
django_run_db_migrations: yes
django_run_collectstatic: yes

django_email_host: ~
django_email_port: 1025
django_email_host_user: ~
django_email_host_password: ~

# Django Environment variables
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  MEDIA_ROOT: "{{ nginx_media_dir }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  DATABASE_URL: "postgres://{{ db_user }}:{{ db_password}}@127.0.0.1:5432/{{ db_name }}"
  DJANGO_EMAIL_HOST: "{{ django_email_host|default(omit) }}"
  EMAIL_PORT: "{{ django_email_port}}"
  EMAIL_HOST_USER: "{{ django_email_host_user|default(omit) }}"
  EMAIL_HOST_PASSWORD: "{{ django_email_host_password|default(omit) }}"
  DJANGO_DEFAULT_FROM_EMAIL: "{{ application_name}} <noreply@{{ ansible_eth0.ipv4.address }}>"
  BROKER_URL: "{{ django_broker_url|default(omit) }}"